RELEASE.md, src/main/scala/uk/ac/wellcome/storage/dynamo/VersionedDao.scala, src/main/scala/uk/ac/wellcome/storage/s3/S3StorageBackend.scala
This is the one change in the platform repo we don't have here yet.
=> Change some logs from INFO to DEBUG

RELEASE.md, src/main/scala/uk/ac/wellcome/storage/s3/S3StorageBackend.scala
=> Patch the S3StorageBackend so streams aren't buffered in memory

RELEASE.md, src/main/scala/uk/ac/wellcome/storage/GlobalExecutionContext.scala, src/test/scala/uk/ac/wellcome/storage/dynamo/VersionedDaoTest.scala, src/test/scala/uk/ac/wellcome/storage/fixtures/LocalDynamoDb.scala
=> Port the new LocalDynamoDb fixtures to the storage lib

RELEASE.md, src/test/scala/uk/ac/wellcome/storage/fixtures/S3.scala
=> Port the new helpers to the S3 fixture

RELEASE.md, project/Dependencies.scala, src/main/scala/uk/ac/wellcome/storage/type_classes/SerialisationStrategy.scala, src/test/scala/uk/ac/wellcome/storage/ObjectStoreTest.scala, src/test/scala/uk/ac/wellcome/storage/fixtures/LocalDynamoDb.scala
=> Use SHA256 instead of MM3 for hashing

RELEASE.md, project/Dependencies.scala, src/main/scala/uk/ac/wellcome/storage/dynamo/VersionedDao.scala, src/main/scala/uk/ac/wellcome/storage/s3/S3StorageBackend.scala, src/main/scala/uk/ac/wellcome/storage/vhs/VersionedHybridStore.scala, src/test/scala/uk/ac/wellcome/storage/fixtures/LocalDynamoDb.scala, src/test/scala/uk/ac/wellcome/storage/fixtures/LocalVersionedHybridStore.scala, src/test/scala/uk/ac/wellcome/storage/fixtures/S3.scala
We're no longer using storage with DI anywhere in the platform, so we can remove this dependency.
=> 🔥 Remove our Guice dependency 🔥

RELEASE.md, storage/src/main/scala/uk/ac/wellcome/storage/s3/S3PrefixCopier.scala, storage/src/main/scala/uk/ac/wellcome/storage/s3/S3PrefixCopierResult.scala, storage/src/main/scala/uk/ac/wellcome/storage/s3/S3PrefixOperator.scala, storage/src/test/scala/uk/ac/wellcome/storage/s3/S3PrefixCopierTest.scala
Add filecount result to prefix copier
=> PrefixCopier result

RELEASE.md, storage/src/test/scala/uk/ac/wellcome/storage/fixtures/S3.scala
Valid bucket name in test fixtures
=> Bucket test fixture

RELEASE.md, storage/src/main/scala/uk/ac/wellcome/storage/s3/S3Copier.scala
Speculative fix for wellcometrust/platform#3600
I haven’t written a test for this because I’m not sure how I’d test it. Open to suggestions!
=> Remember to close the input streams in S3Copier

RELEASE.md, storage/src/main/scala/uk/ac/wellcome/storage/locking/DynamoLockingService.scala, storage/src/test/scala/uk/ac/wellcome/storage/fixtures/DynamoLockingFixtures.scala, storage/src/test/scala/uk/ac/wellcome/storage/fixtures/InMemoryLockDao.scala, storage/src/test/scala/uk/ac/wellcome/storage/locking/InMemoryLockDaoTest.scala, storage_typesafe/src/main/scala/uk/ac/wellcome/storage/typesafe/LockingBuilder.scala
See https://github.com/wellcometrust/storage-service/pull/195
=> Tweaks to the locking services for the replicator

RELEASE.md, storage/src/main/scala/uk/ac/wellcome/storage/dynamo/DynamoDao.scala, storage/src/main/scala/uk/ac/wellcome/storage/dynamo/package.scala, storage/src/main/scala/uk/ac/wellcome/storage/memory/MemoryConditionalUpdateDao.scala, storage/src/main/scala/uk/ac/wellcome/storage/memory/MemoryStorageBackend.scala, storage/src/main/scala/uk/ac/wellcome/storage/memory/MemoryVersionedDao.scala, storage/src/main/scala/uk/ac/wellcome/storage/vhs/VersionedHybridStore.scala, storage/src/main/scala/uk/ac/wellcome/storage/vhs/vhs.scala, storage/src/test/scala/uk/ac/wellcome/storage/memory/MemoryStorageBackendTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/vhs/VHSEntryFormatTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/vhs/VersionedHybridStoreTest.scala
Some wish list items from https://github.com/wellcometrust/platform/issues/3630 plus a fix for the broken build
=> Miscellaneous fixes

RELEASE.md, storage/src/main/scala/uk/ac/wellcome/storage/memory/MemoryObjectStore.scala
Closes wellcometrust/platform#3654.
=> Type the backend of MemoryObjectStore as a memory backend

RELEASE.md, project/Dependencies.scala, storage/src/main/scala/uk/ac/wellcome/storage/dynamo/package.scala, storage/src/main/scala/uk/ac/wellcome/storage/locking/DynamoLockDao.scala, storage/src/main/scala/uk/ac/wellcome/storage/locking/ScanamoHelpers.scala, storage/src/main/scala/uk/ac/wellcome/storage/streaming/Codec.scala, storage/src/test/scala/uk/ac/wellcome/storage/dynamo/DynamoFormatTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/fixtures/DynamoFixtures.scala, storage/src/test/scala/uk/ac/wellcome/storage/fixtures/DynamoLockingFixtures.scala, storage/src/test/scala/uk/ac/wellcome/storage/locking/DynamoLockDaoTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/locking/DynamoLockingServiceTest.scala, storage_typesafe/src/main/scala/uk/ac/wellcome/storage/typesafe/LockingBuilder.scala
=> Upgrade the bundled version of Scanamo

RELEASE.md, storage/src/main/scala/uk/ac/wellcome/storage/StorageError.scala, storage/src/main/scala/uk/ac/wellcome/storage/streaming/Codec.scala, storage/src/main/scala/uk/ac/wellcome/storage/streaming/Decoder.scala, storage/src/main/scala/uk/ac/wellcome/storage/streaming/Encoder.scala, storage/src/main/scala/uk/ac/wellcome/storage/streaming/FiniteInputStream.scala, storage/src/test/scala/uk/ac/wellcome/storage/fixtures/S3Fixtures.scala, storage/src/test/scala/uk/ac/wellcome/storage/generators/ObjectLocationGenerators.scala, storage/src/test/scala/uk/ac/wellcome/storage/generators/RandomThings.scala, storage/src/test/scala/uk/ac/wellcome/storage/streaming/CodecTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/streaming/DecoderTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/streaming/EncoderTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/streaming/StreamAssertions.scala
=> Add FiniteInputStream

RELEASE.md, storage/src/main/scala/uk/ac/wellcome/storage/Identifiable.scala, storage/src/main/scala/uk/ac/wellcome/storage/StorageError.scala, storage/src/main/scala/uk/ac/wellcome/storage/dynamo/DynamoEntry.scala, storage/src/main/scala/uk/ac/wellcome/storage/maxima/Maxima.scala, storage/src/main/scala/uk/ac/wellcome/storage/maxima/dynamo/DynamoHashRangeMaxima.scala, storage/src/main/scala/uk/ac/wellcome/storage/maxima/memory/MemoryMaxima.scala, storage/src/main/scala/uk/ac/wellcome/storage/store/memory/MemoryStoreBase.scala, storage/src/test/scala/uk/ac/wellcome/storage/IdentifiableTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/fixtures/DynamoFixtures.scala, storage/src/test/scala/uk/ac/wellcome/storage/generators/RecordGenerators.scala, storage/src/test/scala/uk/ac/wellcome/storage/maxima/MaximaTestCases.scala, storage/src/test/scala/uk/ac/wellcome/storage/maxima/dynamo/DynamoHashRangeMaximaTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/maxima/memory/MemoryMaximaTest.scala
Another piece spun out of #76.
=> Add the Maxima trait and implementations

RELEASE.md, storage/src/main/scala/uk/ac/wellcome/storage/dynamo/package.scala, storage/src/test/scala/uk/ac/wellcome/storage/dynamo/DynamoFormatTest.scala
=> Improve the DynamoFormat tests; fix a bug

RELEASE.md, storage/src/main/scala/uk/ac/wellcome/storage/StorageError.scala, storage/src/main/scala/uk/ac/wellcome/storage/store/StreamStore.scala, storage/src/main/scala/uk/ac/wellcome/storage/store/memory/MemoryStreamStore.scala, storage/src/main/scala/uk/ac/wellcome/storage/store/s3/S3StreamStore.scala, storage/src/test/scala/uk/ac/wellcome/storage/fixtures/S3Fixtures.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/StreamStoreTestCases.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/fixtures/NamespaceFixtures.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/memory/MemoryStreamStoreTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/s3/S3StreamStoreTest.scala
=> Add an S3 implementation of StreamStore

RELEASE.md, storage/src/main/scala/uk/ac/wellcome/storage/store/s3/S3TypedStore.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/s3/S3TypedStoreFixtures.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/s3/S3TypedStoreTest.scala
Another piece from #76. Depends on #87.
=> Add an S3 implementation of TypedStore

RELEASE.md, storage/src/main/scala/uk/ac/wellcome/storage/ObjectLocation.scala, storage/src/main/scala/uk/ac/wellcome/storage/listing/s3/S3Listing.scala, storage/src/main/scala/uk/ac/wellcome/storage/listing/s3/S3ObjectLocationListing.scala, storage/src/main/scala/uk/ac/wellcome/storage/listing/s3/S3ObjectSummaryListing.scala, storage/src/main/scala/uk/ac/wellcome/storage/transfer/PrefixTransfer.scala, storage/src/main/scala/uk/ac/wellcome/storage/transfer/Transfer.scala, storage/src/main/scala/uk/ac/wellcome/storage/transfer/TransferResult.scala, storage/src/main/scala/uk/ac/wellcome/storage/transfer/memory/MemoryPrefixTransfer.scala, storage/src/main/scala/uk/ac/wellcome/storage/transfer/memory/MemoryTransfer.scala, storage/src/main/scala/uk/ac/wellcome/storage/transfer/s3/S3PrefixTransfer.scala, storage/src/main/scala/uk/ac/wellcome/storage/transfer/s3/S3Transfer.scala, storage/src/test/scala/uk/ac/wellcome/storage/listing/ListingTestCases.scala, storage/src/test/scala/uk/ac/wellcome/storage/listing/fixtures/ListingFixtures.scala, storage/src/test/scala/uk/ac/wellcome/storage/listing/memory/MemoryListingFixtures.scala, storage/src/test/scala/uk/ac/wellcome/storage/listing/memory/MemoryListingTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/listing/s3/S3ListingFixtures.scala, storage/src/test/scala/uk/ac/wellcome/storage/listing/s3/S3ListingTestCases.scala, storage/src/test/scala/uk/ac/wellcome/storage/listing/s3/S3ObjectLocationListingTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/listing/s3/S3ObjectSummaryListingTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/transfer/PrefixTransferTestCases.scala, storage/src/test/scala/uk/ac/wellcome/storage/transfer/TransferTestCases.scala, storage/src/test/scala/uk/ac/wellcome/storage/transfer/fixtures/TransferFixtures.scala, storage/src/test/scala/uk/ac/wellcome/storage/transfer/memory/MemoryPrefixTransferTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/transfer/memory/MemoryTransferFixtures.scala, storage/src/test/scala/uk/ac/wellcome/storage/transfer/memory/MemoryTransferTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/transfer/s3/S3PrefixTransferTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/transfer/s3/S3TransferFixtures.scala, storage/src/test/scala/uk/ac/wellcome/storage/transfer/s3/S3TransferTest.scala
=> Extract the PrefixTransfer trait from the mega-PR

RELEASE.md, storage/src/main/scala/uk/ac/wellcome/storage/locking/memory/MemoryLockDao.scala, storage/src/test/scala/uk/ac/wellcome/storage/locking/LockDaoTestCases.scala
Fixes flaky test requiring thread safety.
=> Makes MemoryLockDao thread-safe

RELEASE.md, storage/src/main/scala/uk/ac/wellcome/storage/StorageError.scala, storage/src/main/scala/uk/ac/wellcome/storage/store/VersionedStore.scala, storage/src/main/scala/uk/ac/wellcome/storage/store/dynamo/DynamoReadable.scala, storage/src/main/scala/uk/ac/wellcome/storage/store/dynamo/DynamoStore.scala, storage/src/main/scala/uk/ac/wellcome/storage/store/dynamo/DynamoWritable.scala, storage/src/main/scala/uk/ac/wellcome/storage/store/memory/MemoryVersionedStore.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/VersionedStoreTestCases.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/dynamo/DynamoHashRangeReadableTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/dynamo/DynamoHashRangeWritableTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/dynamo/DynamoHashReadableTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/dynamo/DynamoHashWritableTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/dynamo/DynamoReadableTestCases.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/dynamo/DynamoVersionedStoreTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/dynamo/DynamoWritableTestCases.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/fixtures/VersionedStoreFixtures.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/memory/MemoryVersionedStoreTest.scala
Adds the VersionedStore with in-memory & DynamoDB implementations.
=> VersionedStore

RELEASE.md, storage/src/main/scala/uk/ac/wellcome/storage/store/dynamo/DynamoHybridStoreWithMaxima.scala, storage/src/main/scala/uk/ac/wellcome/storage/store/dynamo/DynamoVersionedHybridStore.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/dynamo/DynamoVersionedHybridStoreTest.scala
Allow Id, and V to be type parametrised allowing the use of case classes as identifiers.
=> Update the VersionedHybridStore

RELEASE.md, storage/src/main/scala/uk/ac/wellcome/storage/store/s3/S3StreamStore.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/s3/S3StreamStoreTest.scala
Closes https://github.com/wellcometrust/platform/issues/3737
=> Expose the underlying S3 exception when you get DoesNotExistError from S3StreamStore

RELEASE.md, storage/src/test/scala/uk/ac/wellcome/storage/fixtures/S3Fixtures.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/dynamo/DynamoHybridStoreTestCases.scala, storage/src/test/scala/uk/ac/wellcome/storage/store/s3/S3StreamStoreTest.scala
=> Fix a flaky test in DynamoHybridStore

RELEASE.md, storage/src/main/scala/uk/ac/wellcome/storage/transfer/s3/S3PrefixTransfer.scala, storage/src/main/scala/uk/ac/wellcome/storage/transfer/s3/S3Transfer.scala, storage/src/test/scala/uk/ac/wellcome/storage/transfer/s3/S3PrefixTransferTest.scala, storage/src/test/scala/uk/ac/wellcome/storage/transfer/s3/S3TransferTest.scala
For https://github.com/wellcometrust/platform/issues/4096
=> Allow specifying the storage class when using S3Transfer

RELEASE.md, storage/src/main/scala/uk/ac/wellcome/storage/transfer/s3/S3Transfer.scala, storage/src/test/scala/uk/ac/wellcome/storage/transfer/s3/S3TransferTest.scala
Another step towards https://github.com/wellcomecollection/platform/issues/4562
=> Don't copy object tags when using S3Transfer
